import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'zh_CH': {
          "Bumou": "咘呣",
          "Visible psychological pulsation": "看得见的心理脉动",
          "Oops!": "哎呀！",
          "text": "文本",
          "image": "图片",
          "video": "视频",
          "audio": "音频",
          "voice": "语音",
          "Message": "消息",
          "Remove": "删除",
          "Internal server error": "内部服务器错误",
          "Help request already accepted or canceled": "帮助请求已被接受或取消",
          "My help requests will show here": "我的帮助请求将显示在这里",
          "Incoming requests will show here": "传入请求将显示在这里",
          "Available soon, not ready yet.": "即将推出，尚未准备好。",
          "you sent a ": "你发送了一个",
          "you received a ": "你收到了一个",
          " message": "消息",
          "Got it!": "知道了！",
          "Success!": "成功！",
          "Please, check your internet connection": "请检查您的互联网连接",
          "Something went wrong": "出了点问题",
          "Take a photo": "拍照",
          "Choose from gallery": "从图库中选择",
          "Cancel": "取消",
          "Cropper": "裁剪机",
          'Not available yet': '暂时不可用',
          'About': '关于',
          'No Chatrooms': '没有聊天室',
          'Retry': '重试',
          'Post': '发布',
          'No Messages, Start Chatting': '没有消息，开始聊天',
          'Feedback or Support': '反馈或支持',
          'Our email address copied to your clipboard': '我们的电子邮件地址已复制到剪贴板',
          'Friend removed successfully': '朋友已成功删除',
          // Login Screen
          'Please accept the terms of service': '请接受服务条款',
          'I accept the ': '我接受 ',
          'Terms of Service': '服务条款',
          'Log In': '登 录',
          'Log in': '登 录',
          'Login': '登录',
          'Adult': '成人',
          'Student': '学生',
          'Categories': '选择',
          'Email': '邮箱',
          'Email:': '邮箱:',
          'Email, Phone or Username': '电子邮件，电话或用户名',
          'Password': '密码',
          "Don't have an account?": '还没有帐户？',
          //  Sign Up Screen
          'Sign Up': '注册',
          'Country:': '国家:',
          'Country': '国家',
          'City:': '城市:',
          'City': '城市',
          'First Name': '名',
          'First Name:': '名:',
          'Last Name:': '姓:',
          'Last Name': '姓',
          'School Name:': '学校名称:',
          'School Name': '学校名称',
          'City name': '城市',
          'Country name': '国家',
          'Class Name:': '班级名称:',
          'Class Name': '班级名称',
          'Teacher Name:': '老师姓名:',
          'Teacher Name': '老师姓名',
          'Mobile No': '手机号码',
          'Mobile No:': '手机号码:',
          'Username': '用户名',
          'User Name:': '用户名:',
          'Language': '语言',
          'Already have an account?': '已经有帐户？',
          'Privacy Policy': '隐私政策',
          'By signing up you agree to our ': '注册即表示您同意我们的 ',
          // profile Screen
          'Edit Profile': '编辑个人资料',
          'Profile': '我',
          'Emoji': '心情',
          'Chart': '分析',
          'Chat': '信息',
          'Moments': '空间',
          'Help': '帮助',
          'Save': '保存',
          'Delete Account': '删除帐户',
          'Delete': '删除',
          'Logout': '登出',
          'Are you sure you want to delete your account?': '您确定要删除帐户吗？',
          'Are you sure you want to logout?': '您确定要注销吗？',
          // Feelings Screen
          'VERY GOOD': '非常好',
          'VERYGOOD': '非常好',
          'GOOD': '好',
          'BAD': '不好',
          'VERY BAD': '很不好',
          'VERYBAD': '很不好',
          'NEUTRAL': '一般',
          'EXCITED': '兴奋',
          'How do you feel?': '你好吗?',
          'This is wonderful. Do you want to share it and make everyone happy for you?':
              '这太棒了。你想分享它并让每个人都为你高兴吗？',
          'Keep this good mood and the day will be smooth.':
              '保持这样的好心情，这一天就会顺利。',
          'Don\'t care about the bad things, try to look towards the good things.':
              '不要在意那些不好事情，保持积极向上，加油！',
          "What happened? Do you want a hug? Tell me, let's disscuss what to do together.":
              "发生了什么事？给你的一个大大的拥抱，告诉我，让我们一起解决吧。",
          'Smile at yourself,something good may be will happen.':
              '对自己微笑，也许会发生好事。',
          'This is wonderful. Do you want to share it and make evveryone happy for you':
              '这太棒了。你想分享它并让每个人都为你高兴吗',
          // Your MOODWEEK
          'Your MOODWEEK': '你的心情周',
          'Your ': '你的',
          'MOODWEEK': '心情周',
          'Weekly': '周',
          'Monthly': '月',
          'Yearly': '年',
          // Chat Screen
          'Messages': '留言',
          'Type a message': '输入消息',
          'Search anything....': '搜索任何东西....',
          'Camera': '相机',
          'Gallery': '画廊',
          //Friends Screen
          'All Friends': '所有朋友',
          'Add Friends': '添加朋友',
          'Add Friend': '添加朋友',
          'Friends': '朋友们',
          'Search': '搜索',
          'Pending': '待办的',
          'No Pending Request': '没有待处理的请求',
          'No Friends': '没朋友',
          'Online': '在线的',
          'Offline': '离线',
          'Confirm': '确认',
          'Request sent successfully': '请求发送成功',
          'No User Found': '未找到用户',
          // Moments Screen
          "What's on your mind?": '你在想什么？',
          'likes': '喜欢',
          'You can\'t upload more than 40MB': '您不能上传超过40MB',
          'You can\'t upload more than 10 images': '您不能上传超过10张图片',
          'Long press to stop': '长按停止',
          'Ring': '铃声',
          'Is Anonymous': '匿名',
          'Your identity will be hidden': '您的身份将被隐藏',
          // Help Screen
          'End Help Request': '结束帮助请求',
          'Are you in Emergency?': '你有紧急情况吗？',
          'Press the button below to trigger an alarm that will help people know that you are in trouble.':
              '按下面的按钮触发警报，这将帮助人们知道你有麻烦。',
          'Are you sure?': '你确定吗？',
          'You are about to turn off the emergency help feature? You will no longer be able to get or send help requests':
              '您要关闭紧急帮助功能吗？您将无法再获取或发送帮助请求',
          'Turn off': '关',
          'You have turned off the emergency feature': '您已关闭紧急功能',
          'Please turn on the emergency feature to send and receive the requests':
              '请开启紧急功能以发送和接收请求',
          'Send a message': '发送消息',
          'Type your message here': '在这里输入您的消息',
          'Send': '发送',
          'Write your response here': '在这里写下您的回应',
          'Response:': '回应:',
          'Send Response': '发送回应',
          'Request Details:': '请求详情:',
          'Requested By:': '请求者:',
          'Help Request Details': '帮助请求详情',
          'Please enter response message': '请输入响应消息',
          'Help request': '帮助请求',
          'Help is on going': '帮助正在进行',
          'Help asked by:': '帮助请求者:',
          'Help requested by:': '帮助请求者:',

          // Error Screen
          'Please try again later': '请稍后再试',
          'Error': '错误',
          'Failed': '失败',
          'Success': '成功',
          'Warning': '警告',
          'Info': '信息',
          'Got it': '知道了',
          '''Smile at yourself, something good may be will happen.''':
              '对自己微笑，也许会发生好事。',
          'Type Here': '在这里输入',
          'Continue': '继续',
          'Call': '电话',
          'Moment': '时刻',
          'Unknown media type': '未知的媒体类型',
          'Waiting to record': '等待录制',
          'Please fill all the fields': '请填写所有字段',
          'This field is required': '此字段为必填项*',
          'Please enter a valid email address': '请输入有效的电子邮件地址',
          'Email already exists': '电子邮件已存在',
          'Email is required': '电子邮件是必需的',
          'Invalid email address': '无效的电子邮件地址',
          'Password is required': '密码是必需的',
          'Password must be at least 6 characters': '密码必须至少6个字符',
          'Password must be at least 6 digits long': '密码必须至少6位数字',
          'Password must not be more than 20 digits long': '密码长度不能超过20位',
          'Create Post': '创建帖子',
          'Whats on your mind?': '你在想什么？',
          'Likes': '喜欢',
          'comments': '评论',
          'Comments': '评论',
          'Add your comment': '添加您的评论',
          'Add a comment': '添加评论',
          'No Likes yet': '还没有喜欢',
          'No comments yet': '还没有评论',
          'No Posts yet. Pull to refresh': '还没有帖子。点击刷新',
          //common
          'No Data Found': '没有找到数据',
          'Report': '举报',
          "Block user": '屏蔽用户',
          'User blocked successfully': '用户已成功屏蔽',
          'adult': '成人',
          'ADULT': '成人',
          'student': '学生',
          'STUDENT': '学生',
          'hours ago': '小时前',
          'minutes ago': '分钟前',
          'Just now': '现在',
          // permissions
          'Allow': '允许',
          'Storage Permission': '存储权限',
          'App needs storage permission to select video for your post or chat.':
              '应用程序需要存储权限以选择视频进行帖子或聊天。',
          'Gallery Permission': '图库权限',
          'App needs gallery permission to select photo for profile, post or chat.':
              '应用程序需要图库权限以选择个人资料，帖子或聊天的照片。',
          'Camera Permission': '相机权限',
          'App needs camera permission to take photo for profile, post or chat.':
              '应用程序需要相机权限以为个人资料，帖子或聊天拍照。',
          'Microphone Permission': '麦克风权限',
          'App needs microphone permission to record audio for voice chat.':
              '应用程序需要麦克风权限以录制语音聊天的音频。',
          'Location Permission': '位置权限',
          'App needs location permission to get your current location for chat.':
              '应用程序需要位置权限以获取您的当前位置进行聊天。',
          'Notification Permission': '通知权限',
          'App needs notification permission to send you notification about various activities.':
              '应用程序需要通知权限以向您发送有关各种活动的通知。',
          'Privacy Policy & Terms of Services': "隐私政策和服务条款",
          'Privacy Policy Agreement': '隐私政策协议',
          'Welcome to Bumou 咘呣': '欢迎来到咘呣',
          'Before you continue, please take a moment to read and understand our Privacy Policy. This will explain how we handle your personal information.':
              '在继续之前，请花点时间阅读并了解我们的隐私政策。这将解释我们如何处理您的个人信息。',
          'You can review the Privacy Policy at any time by visiting':
              '您可以随时访问隐私政策',
          'Accept All': '全部接受',
          'Decline': '下降',
          'Privacy Policy Pending': '隐私政策待定',
          'Please accept the privacy policy to continue': '请接受隐私政策以继续',
          'Open Privacy Policy': '打开隐私政策',
          "Accept": "接受",
          "Reject": "拒绝",
          "Help request cancelled": "帮助请求已取消",
          "Need help here": "这里需要帮助",
          "Help request sent": "帮助请求已发送",
          "Cancel Request": "取消请求",
          "Request Help": "请求帮助",
          "Incoming requests": "传入请求",
          "Ongoing help": "正在进行的帮助",
          "Pull down to refresh": "下拉刷新",
          "No incoming help requests": "没有传入的帮助请求",
          "Unknown": "未知",
          "Need help": "需要帮助",
          "joined the chat": "加入了聊天",
          "message": "消息",
          "New Help Request": "新帮助请求",
          "Please accept the help requests": "请接受帮助请求",
          "Are you sure you want to delete this chat?": "您确定要删除此聊天吗？",
          "Chat Deleted successfully": "聊天已成功删除。",
          "Help Deleted successfully": "聊天已成功删除。",
          "Are you sure you want to delete this ongoing help?": "您确定要删除此持续帮助吗？",
          "What happened? Do you want a hug? Tell me, let's discuss what to do together.":
              "很不好：发生了什么事？给你的一个大大的拥抱，告诉我，让我们一起解决吧。"
        },
      };
}
