name: app
description: Bumou Mobile app
publish_to: "none"

version: 1.3.1+2016

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pushy_flutter: ^2.0.27
  cupertino_icons: ^1.0.2
  firebase_core: ^3.6.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  # dropdown_textfield: ^1.0.8
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  fl_chart: ^0.69.0
  dio: ^5.3.3
  hive_flutter: ^1.1.0
  form_field_validator: ^1.1.0
  pull_to_refresh: ^2.0.0
  lottie: ^3.1.1
  image_picker: ^0.8.5+3
  permission_handler: ^11.0.1
  image_cropper: ^8.0.2
  icons_launcher: ^3.0.0
  video_player: ^2.8.1
  intl: ^0.18.0
  geolocator: ^13.0.1
  just_audio: ^0.9.36
  # home_widget: ^0.4.0
  # Live features
  flutter_webrtc: ^0.11.7
  # socket_io_client: ^2.0.3+1
  socket_io_client: ^3.0.0-beta.2
  video_thumbnail: ^0.5.3
  mime: ^1.0.4
  # flutter_ringtone_player: ^4.0.0+2
  carousel_slider: ^5.0.0
  popup_menu_2: ^0.1.1
  record: ^5.0.1
  path_provider: ^2.1.1
  audioplayers: ^6.0.0
  audio_waveforms: ^1.0.4
  url_launcher: ^6.2.2
  ripple_wave: ^0.1.3
  auto_size_text: ^3.0.0
  visibility_detector: ^0.4.0+2
  selectable_autolink_text: ^2.6.0
  share_plus: ^10.0.2
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  flutter_ringtone_manager: ^1.1.2
  flutter_ringtone_player: ^4.0.0+3
  flutter_slidable: ^3.1.1
  syncfusion_flutter_charts: ^27.1.50
  syncfusion_flutter_sliders: ^27.1.50
  native_toast: ^0.0.2
  flutter_local_notifications: ^17.2.2
  flutter_app_badger: ^1.5.0
  aliyun_push: ^0.1.6
  shared_preferences:
  unlock_detector: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.1.0

icons_launcher:
  image_path: "assets/images/logo.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/Animation/
    - assets/sounds/
    - assets/bitmap/
